move changes file in _reject_changefile() too
If we forget to move foo.changes, mini-dinstall wait for the other files
(.deb, .dsc, ...) in hope for upload. When the max_retry_time (default 2
days) reaches, he use _reject_changefile() again, to reject the upload.
Thereafter mini-dinstall crash, because he can't move vanished files.

Aug 29 19:52:29 mini-dinstall [-1218184272] INFO: Upload "/home/debian-packages/foo_0.1_i386.changes" isn't complete; marking for retry in 960 seconds
Aug 29 20:08:29 mini-dinstall [-1218184272] ERROR: Unhandled exception while rejecting /home/debian-packages/foo_0.1_i386.changes; archive may be in inconsistent state
Aug 29 20:08:30 mini-dinstall [-1218184272] ERROR: Unhandled exception; shutting down
Traceback (most recent call last):
  File "./mini-dinstall", line 508, in run
  File "./mini-dinstall", line 642, in _daemonize
  File "./mini-dinstall", line 570, in _reject_changefile
  File "./mini-dinstall", line 753, in reject
  File "./mini-dinstall", line 975, in _reject_changefile
  File "./mini-dinstall", line 174, in do_rename
OSError: [Errno 2] No such file or directory
Aug 29 20:08:30 mini-dinstall [-1210273024] INFO: Die event caught; waiting for incoming processor to finish